# Generated by Django 5.2.1 on 2025-06-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=100, unique=True)),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('shift_name', models.CharField(max_length=50)),
                ('enc_offer_id', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
