# Generated by Django 5.2.1 on 2025-06-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_facultycourse_delete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycourse',
            name='offer_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='facultycourse',
            name='shift_name',
            field=models.CharField(max_length=100),
        ),
    ]
