# Generated by Django 5.2.1 on 2025-06-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_facultycourse_offer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.facultycourse'),
        ),
    ]
