# Generated by Django 5.2.1 on 2025-06-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_email_otp_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created_at',
        ),
    ]
